@startuml

class User{
	- id : Long
	- firstName : String
	- lastName : String
	- phoneNumber : String
	- email : String
	- username : String
	- password : String
	- nationalCode : String
	- birthDay : Date
	- createdAt : Date
	- updatedAt : Date
	- deletedAt : Date

	+ clone() : User
	+ setterAttributes ()
	+ getterAttributes ()
}

class UserTest {
    + prototypeDesignPatternTest() : void
}

interface Cloneable
User ..|> Cloneable
UserTest ..> User

@enduml