@startuml
class DBConnection{
   - connection : Connection
   - {static} dbConnection : DBConnection
   ==
   - DBConnection()
   + {static} getDBConnection() : DBConnection
   + getConnection() : Connection
}

DBConnection -> DBConnection
@enduml