@startuml
class DBConnection {
   - connection : Connection
   - {static} dbConnection : DBConnection

   - DBConnection()
   + {static} getDBConnection() : DBConnection
   + getConnection() : Connection
}

class Config {
   - properties : Properties
   - {static} config : Config

   - Config()
   + {static} getConfig() : Config
}

class DBConnectionTest {
    + hashCodeTest() : void
    + performanceTest() : void
    + DBH2Test() : void
}

DBConnection "1"<--*"1" DBConnection
Config "1"<--*"1" DBConnection
Config "1"<--*"1" Config
DBConnectionTest ..> DBConnection

@enduml